apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: {{ .Values.helloService.service.type }}
  ports:
    - port: {{ .Values.helloService.service.port }}
      targetPort: {{ .Values.helloService.service.port }}
  selector:
    app: hello-service
