apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  type: {{ .Values.profileService.service.type }}
  ports:
    - port: {{ .Values.profileService.service.port }}
      targetPort: {{ .Values.profileService.service.port }}
  selector:
    app: profile-service
